language: php

sudo: false

notifications:
  on_success: never
  on_failure: change

php:
  - 7.2

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  - composer install --dev
  # After CodeSniffer install you should refresh your path.
  - phpenv rehash
  # Install ESLint.
  - npm install -g eslint
  - npm install -g eslint-config-wordpress

script:
  - mkdir -p build/logs
  # Run the plugin through ESLint.
  - eslint .
  # PHPCS Coding Standards check.
  # @link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
  # @link https://github.com/PHPCompatibility/PHPCompatibilityWP
  # @link http://pear.php.net/package/PHP_CodeSniffer/
  # -p flag: Show progress of the run.
  # -s flag: Show sniff codes in all reports.
  # -v flag: Print verbose output.
  - packages/bin/phpcs -v --runtime-set ignore_warnings_on_exit 1
